import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
// import {Navbar} from "../components/Navbar";
import "../css/home.css";
// import 'bootstrap/dist/css/bootstrap.min.css';
import { Carousel } from 'react-bootstrap';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCheckCircle, faBullseye, faHeart } from '@fortawesome/free-solid-svg-icons';
export const Home = () => {
    return (
      <div
      >
        
  
        {/* Title */}
        <section id="title">
      <div className="container-fluid">
        <div className="row">
          <div className="col-lg-6">
            <h1 className="big-heading">Pitch Perfect</h1>
            <h2>Create a poll to gather quick feedback, forecast voting behaviour, or guide marketing strategy. Any device may use it, and it is quick and free.</h2>
            <a className="btn btn-dark btn-outline-light btn-lg downloadbutton" href="/register" role="button">New to the website?</a>
          </div>
          
        </div>
      </div>
      <div className="anuj">
        <img src="/public/images/home.png" alt="" />
      </div>
    </section>
  
        {/* Testimonials */}
        <section id="features">
      <div className="container-fluid">
        <div className="row">
          <div className="feature_p col-lg-4">
            <FontAwesomeIcon icon={faCheckCircle} size="4x" />
            <h3 className="feature-size">Cost savings:</h3>
            <p>Online voting systems can save money compared to traditional voting methods.</p>
          </div>
          <div className="feature_p col-lg-4">
            <FontAwesomeIcon icon={faBullseye} size="4x" />
            <h3 className="feature-size">Accessibility:</h3>
            <p>Online voting systems make voting more accessible for people with disabilities.</p>
          </div>
          <div className="feature_p col-lg-4">
            <FontAwesomeIcon icon={faHeart} size="4x" />
            <h3 className="feature-size">Faster results: </h3>
            <p>Online voting systems can provide faster results, as the votes are tallied automatically.</p>
          </div>
        </div>
      </div>
    </section>





    <section id="testimonials">
        <Carousel id="carouselExampleControls" className="hellobhai" data-ride="false">
          <Carousel.Item className="container-fluid">
            <img className="check" src="/images/Section.png" alt="" />
            <Carousel.Caption>
              <h3 className="test-size">
                You can create polls to gather quick feedback, forecast voting behavior, or guide marketing strategy. It's easy and free to use, and you can share your polls with anyone using a unique link generated by our system.
              </h3>
            </Carousel.Caption>
          </Carousel.Item>
          <Carousel.Item className="container-fluid">
            <img className="check" src="/images/Another.png" alt="" />
            <Carousel.Caption>
              <h3 className="testimonial-text test-size">
                If you receive a link to a poll, you can easily cast your vote with just a few clicks. Join the thousands of users who have already created and voted in polls on our platform.
                <br /> Try it out today!
              </h3>
            </Carousel.Caption>
          </Carousel.Item>
        </Carousel>
      </section>

    <section id="pricing">
      <div className="pricing-container">
        <h2 className="pricing-size">Make your voice heard with our seamless online voting system.</h2>
        <p>Revolutionizing the Way You Cast Your Vote: Say Goodbye to Traditional Voting Systems</p>
      </div>
    </section>
  
        {/* Pricing */}
        <section id="cta">
  <div className="cta-item container-fluid">
    <div className="row justify-content-center">
      <div className="pricing-item col-lg-4">
        <div className="card">
          <div className="card-header">
            <h3 className="small-size">Anuj Munjal</h3>
          </div>
          <div className="card-body">
            <a href="mailto:anujmunjal08@gmail.com">
              <button className="btn btn-lg btn-block btn-outline-dark" type="button">
                Send Email
              </button>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div className="last" style={{ marginBottom: 0 }}>
      <img src="images/home2.png" alt="" />
    </div>
  </div>
</section>

      </div>
    );
  };
  